DATA_DIRECTORY = "/Users/erdicalli/dev/workspace/data"
ADE_20K_VERSION = "ADE20K_2016_07_26"
ADE_20K_MAT_FILE = DATA_DIRECTORY + '/' + ADE_20K_VERSION + '/index_ade20k.mat'
INDEX_FILE = "index"
TRAINING_DATA_DIRECTORY = DATA_DIRECTORY + '/' + ADE_20K_VERSION  + "/images/training/"
VALIDATION_DATA_DIRECTORY = DATA_DIRECTORY + '/' + ADE_20K_VERSION  + "/images/validation/"
IMAGE_WIDTH = 384
IMAGE_HEIGHT = 384
